`timescale 1ns / 1ps

module memory_python #(parameter N = 4)(data, address, read_enable); //N parameter can be set up to certain needs.

	input [N -1:0] address;
	input read_enable;
	output [N -1:0] data;
	reg [N -1:0] mem [0:(2**N )-1];

	assign data = read_enable ? mem[address]:'b0;

initial begin

    $readmemb("rom_16x4.dat", mem); // reading the from the code that was generated by Python

end

endmodule
